# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmi < Formula
  desc "Claude Code Bash command approval hook"
  homepage "https://github.com/dgerlanc/mmi"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.3.1/mmi_0.3.1_darwin_amd64.tar.gz"
      sha256 "7e0809c50c0289044e6d57fda22f054adfe2d5e13de16a5b779088d955a09e90"

      define_method(:install) do
        bin.install "mmi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.3.1/mmi_0.3.1_darwin_arm64.tar.gz"
      sha256 "5632c8c20a180c129900a55e33556b15623e617cfb74155aaf20fbae7cfc7ffc"

      define_method(:install) do
        bin.install "mmi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.3.1/mmi_0.3.1_linux_amd64.tar.gz"
      sha256 "ee1ee0c2b7bb6e6cfbc0cfb636ffd5f0500be6a7cc341e8be8d43392bfd2e460"
      define_method(:install) do
        bin.install "mmi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.3.1/mmi_0.3.1_linux_arm64.tar.gz"
      sha256 "e497b1308bd61c6194e5c8a8379c356f9538e124148bf49903321f427a234aae"
      define_method(:install) do
        bin.install "mmi"
      end
    end
  end
end
