# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmi" do
  name "mmi"
  desc "Claude Code Bash command approval hook"
  homepage "https://github.com/dgerlanc/mmi"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmi"

  on_macos do
    on_intel do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_darwin_amd64.tar.gz"
      sha256 "9757d07d0bf6fc7b30a24f6b587e492b5efa6c34cb3f6c20e46364adbb5c9abb"
    end
    on_arm do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_darwin_arm64.tar.gz"
      sha256 "8162d8b7729110417c93cf14a2bfe1155334a8cd5f466347fc7176335b90e90b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_linux_amd64.tar.gz"
      sha256 "25d477d35795b1915b9d80427beca6db1dc624f5689eb93042a60aee4c546b8c"
    end
    on_arm do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_linux_arm64.tar.gz"
      sha256 "54c3d47e46508e002cd036da038fa322573386385f456d9e879fabb3435a8444"
    end
  end

  # No zap stanza required
end
