# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmi" do
  name "mmi"
  desc "Claude Code Bash command approval hook"
  homepage "https://github.com/dgerlanc/mmi"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmi"

  on_macos do
    on_intel do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_darwin_amd64.tar.gz"
      sha256 "55c27eb9213fb40cc899524939f1f734520063dbaa1c0d2cf4e33e6d441556c5"
    end
    on_arm do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_darwin_arm64.tar.gz"
      sha256 "41951fc9b3081c027baf949fa06d0fee628df6434d50e7ac65e2aec7429a1735"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_linux_amd64.tar.gz"
      sha256 "f84164dd4689a7dedb11f3d1afe81db9846a72ca6c0022c9d190950c26663a23"
    end
    on_arm do
      url "https://github.com/dgerlanc/mmi/releases/download/v#{version}/mmi_#{version}_linux_arm64.tar.gz"
      sha256 "a9117e8bf2f8977cdfd821826c383360f43ec9d2fb3ac4cdeb398acef59d8266"
    end
  end

  # No zap stanza required
end
