# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmi < Formula
  desc "Claude Code Bash command approval hook"
  homepage "https://github.com/dgerlanc/mmi"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.1.4/mmi_0.1.4_darwin_amd64.tar.gz"
      sha256 "31d1605902792969ad500b5c7f6705019b59489fe53b4c32dfecdeb351fd5da4"

      def install
        bin.install "mmi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.1.4/mmi_0.1.4_darwin_arm64.tar.gz"
      sha256 "3786197b1be597bfc6de7f7f09a2ab91a97ba8639d13920cddc0fa0206d1db66"

      def install
        bin.install "mmi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.1.4/mmi_0.1.4_linux_amd64.tar.gz"
      sha256 "80ac7fed10aa720ec602b43b237fc01d6b9110d15bf63e18b108a509c5b81def"
      def install
        bin.install "mmi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dgerlanc/mmi/releases/download/v0.1.4/mmi_0.1.4_linux_arm64.tar.gz"
      sha256 "15e5203fd5e866a71e323ea03f049650e49979738000680dd369762f2909c7bb"
      def install
        bin.install "mmi"
      end
    end
  end

  test do
    system "#{bin}/mmi", "--version"
  end
end
